=== Shylex96/1DAM_2TR_LM/ejerciciosTema4_xml-xsd/ejercicio38.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="personas">
    <xs:complexType>
        <xs:sequence>
            <xs:element name="persona" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="nombre" type="xs:string"></xs:element>
                        <xs:element name="apellidos" type="xs:string"></xs:element>
                        <xs:element name="telefono" type="xs:integer"></xs:element>
                    </xs:sequence>
                    <xs:attribute name="dni" use="required">
                        <xs:simpleType>
                            <xs:restriction base="xs:string">
                                <xs:pattern value="[0-9]{8}[A-Z]"></xs:pattern>
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:attribute>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
</xs:element>
</xs:schema>

=== Shylex96/1DAM_2TR_LM/ejerciciosTema4_xml-xsd/ejercicio38.xml
<?xml version="1.0" encoding="UTF-8"?>
<personas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ejercicio38.xsd">
    <persona dni="12345678Z">
        <nombre>Juan</nombre>
        <apellidos>García</apellidos>
        <telefono>924555555</telefono>
    </persona>
    <persona dni="87654321A">
        <nombre>Luisa</nombre>
        <apellidos>Pérez</apellidos>
        <telefono>954521235</telefono>
    </persona>
</personas>
