<?xml version="1.0" encoding="UTF-8" standalone="yes"?>

<!DOCTYPE personas [
    <!ELEMENT personas (datospersonales+, datoslaborales)>
    <!ELEMENT datospersonales (nombre, apellidos, direccion, telefono, email*, foto, pie)>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT apellidos (#PCDATA)>
    <!ELEMENT direccion (#PCDATA)>
    <!ELEMENT telefono (#PCDATA)>
    <!ELEMENT email (#PCDATA)>
    <!ELEMENT foto EMPTY>
    <!ELEMENT pie (#PCDATA)>
    <!ELEMENT datoslaborales (empresa, direccion, cp)>
    <!ELEMENT empresa (#PCDATA)>
    <!ELEMENT cp (#PCDATA)>

    <!ATTLIST datospersonales edad CDATA #FIXED "18">
    <!ATTLIST foto src CDATA "./nodisponible.jpg">

    <!ENTITY copyright "@Esteban">
    <!ENTITY anyo "2022">
]>

<personas>
    <datospersonales>
        <nombre>Pedro</nombre>
        <apellidos>Ramírez Gonzalo</apellidos>
        <direccion>Calle ancha</direccion>
        <telefono>666666666</telefono>
        <email>yo@yo.com</email>
        <foto src="" />
        <pie>&copyright; &anyo;</pie>
    </datospersonales>
    <datospersonales edad="18">
        <nombre>Pedro</nombre>
        <apellidos>Ramírez Gonzalo</apellidos>
        <direccion>Calle ancha</direccion>
        <telefono>666666666</telefono>
        <email>yo@yo.com</email>
        <foto src="" />
        <pie>&copyright; &anyo;</pie>
    </datospersonales>
    <datoslaborales>
        <empresa>Empresa S.A.</empresa>
        <direccion>CCC</direccion>
        <cp>41008</cp>
    </datoslaborales>
</personas>
