<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE biblioteca [

<!ELEMENT biblioteca (libros)>
<!ELEMENT libros (libro+)>
<!ELEMENT libro (titulo, autores, editorial, descripcion)>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT autores (autor+)>
<!ELEMENT autor (#PCDATA)>
<!ELEMENT editorial (#PCDATA)>
<!ELEMENT descripcion (#PCDATA)>

]>



<biblioteca>

    <libros>
        <libro>
            <titulo>El Quijote</titulo>
        <autores>
            <autor>Miguel de Cervantes</autor>
        </autores>
        <editorial>Anaya</editorial>
        <descripcion>Burla de las novelas de caballería</descripcion>
        </libro>
        <libro>
            <titulo>Buenos Presagios</titulo>
        <autores>
            <autor>Neil Gaiman</autor>
            <autor>Terry Pratchett</autor>
        </autores>
        <editorial>McGraw Hill</editorial>
        <descripcion>Comedia de tono irónico sobre el anticristo</descripcion>
        </libro>
    </libros>

</biblioteca>
